name: loan_repay_pred_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - alembic=1.13.1
  - arrow=1.2.3
  - asttokens=2.4.1
  - binaryornot=0.4.4
  - black=24.3.0
  - blas=1.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - certifi=2024.2.2
  - chardet=4.0.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - colorlog=6.8.2
  - comm=0.2.2
  - contourpy=1.2.0
  - cookiecutter=2.5.0
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - greenlet=3.0.1
  - idna=3.4
  - importlib-metadata=7.0.2
  - importlib_metadata=7.0.2
  - importlib_resources=6.3.1
  - intel-openmp=2023.1.0
  - ipykernel=6.29.3
  - ipython=8.22.2
  - isort=5.13.2
  - jedi=0.19.1
  - jinja2=3.1.3
  - joblib=1.2.0
  - jpeg=9e
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - kiwisolver=1.4.4
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libllvm14=14.0.6
  - libpng=1.6.39
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - llvmlite=0.42.0
  - lz4-c=1.9.4
  - mako=1.3.2
  - markdown-it-py=2.2.0
  - markupsafe=2.1.3
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - mdurl=0.1.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - numba=0.59.0
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.4.0
  - openssl=3.0.13
  - optuna=3.5.0
  - packaging=24.0
  - pandas=2.2.1
  - parso=0.8.3
  - pathspec=0.12.1
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=23.3.1
  - platformdirs=4.2.0
  - prompt-toolkit=3.0.42
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.15.1
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.11.8
  - python-dateutil=2.8.2
  - python-slugify=5.0.2
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - readline=8.2
  - requests=2.31.0
  - rich=13.3.5
  - scikit-learn=1.2.2
  - scipy=1.11.4
  - seaborn=0.12.2
  - setuptools=68.2.2
  - shap=0.42.1
  - six=1.16.0
  - slicer=0.0.7
  - sqlalchemy=2.0.25
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tbb=2021.8.0
  - text-unidecode=1.3
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - tornado=6.3.3
  - tqdm=4.66.2
  - traitlets=5.14.2
  - typing-extensions=4.10.0
  - typing_extensions=4.10.0
  - tzdata=2024a
  - unidecode=1.2.0
  - urllib3=2.1.0
  - wcwidth=0.2.13
  - wheel=0.41.2
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
